name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ranaosamaa

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "generate 3D profile"
          git push
